# Generated by Django 3.2.15 on 2022-08-25 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='e_waste_site',
            new_name='EWasteSite',
        ),
    ]
